### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by abmarnie** [dignitydignity/easter-jam-2024#3]
- [x] ~~Pause menu~~
    - [x] ~~Resume button~~
    - [x] ~~Settings menu~~
        - [x] Full screen toggle
        - [ ] Resolution options
        - [x] Volume toggle
        - [x] Mouse sensitivity
        - [x] Back button
    - [x] ~~Exit button~~

**Comment by fr0gstore** [comment]
my penis is vevry big
